export const baseStrings = {
  // Brand
  app_name: "ChessMaster",

  // Nav & header
  nav_play: "Play",
  nav_problems: "Problems",
  nav_analyze: "Analyze",
  nav_about: "About",
  header_nickname: "Nickname",
  header_profile: "Profile",
  header_settings: "Settings",
  header_logout: "Log Out",
  header_signup: "Sign up",
  header_signin: "Sign In",
  header_user: "User",

  // Common
  cancel: "Cancel",
  save_changes: "Save changes",
  retry: "Retry",
  loading: "Loading…",
  processing: "Processing…",
  email: "Email",
  username: "Username",
  password: "Password",
  confirm_password: "Confirm Password",
  placeholder_email: "your.email@example.com",
  placeholder_username: "Choose a username",
  placeholder_password: "Enter your password",
  placeholder_confirm_password: "Confirm your password",
  remember_me: "Remember me",
  forgot_password: "Forgot password?",
  or_continue_with: "or continue with",
  google: "Google",
  white: "White",
  black: "Black",
  me: "Me",
  opponent: "Opponent",
  bot: "Bot",
  platform: "Platform",
  unknown: "Unknown",
  new_game: "New Game",
  resign: "Resign",
  board_colors: "Board Colors",
  start_game: "Start Game",
  starting: "Starting…",
  start_playing: "Start Playing",
  watch_demo: "Watch Demo",
  login_register: "Login / Register",
  moves: "moves",
  moves_count: "{{count}} moves",
  you_label: "You",
  win: "Win",
  loss: "Loss",
  draw_label: "Draw",
  vs_player: "vs Player",
  vs_bot: "vs Bot",

  // Auth modals
  welcome_back: "Welcome back!",
  log_in: "Log In",
  sign_up: "Sign Up",
  join_chessmaster: "Join ChessMaster",
  create_account_subtitle: "Create an account to start mastering chess",
  create_account: "Create Account",
  reset_password: "Reset Password",
  reset_password_subtitle:
    "Enter your email address and we'll send you a link to reset your password.",
  send_reset_link: "Send Reset Link",
  back_to_sign_in: "Back to Sign In",
  remember_password: "Remember your password? ",
  already_have_account: "Already have an account? ",
  dont_have_account: "Don't have an account? ",
  registration_success: "Registration successful! Please sign in.",

  // Home
  master_chess_title: "Master the Art of Chess",
  master_chess_subtitle:
    "Elevate your game with AI-powered analysis, expert instruction, and a global community of chess enthusiasts.",
  play_chess_title: "Play Chess",
  your_way: "Your Way",
  play_chess_subtitle:
    "Challenge our advanced AI bots or compete against players worldwide in real-time matches.",
  tools_section_title: "Everything You Need to Excel",
  tools_section_subtitle:
    "Comprehensive tools and features designed to take your chess skills to the next level",
  free_account_title: "Ready to Begin Your Journey?",
  free_account_subtitle:
    "Join thousands of players improving their game every day with ChessMaster.",
  create_free_account: "Create Free Account",
  tool_play_games: "Play Games",
  tool_play_desc:
    "Challenge opponents from around the world or sharpen your skills against our advanced AI.",
  tool_play_link_1: "Play against AI Bot",
  tool_play_link_2: "Real-time multiplayer",
  tool_play_link_3: "Join tournaments",
  tool_play_link_4: "Ranked & casual modes",
  tool_solve_problems: "Solve Problems",
  tool_solve_desc:
    "Master tactical patterns and strategic concepts with thousands of curated puzzles.",
  tool_solve_link_1: "Browse by category",
  tool_solve_link_2: "Theme-based puzzles",
  tool_solve_link_3: "Daily challenges",
  tool_solve_link_4: "Difficulty levels",
  tool_analyze_games: "Analyze Games",
  tool_analyze_desc:
    "Deep dive into your games with powerful AI analysis and identify areas for improvement.",
  tool_analyze_link_1: "Computer analysis",
  tool_analyze_link_2: "Move-by-move breakdown",
  tool_analyze_link_3: "Mistake detection",
  tool_analyze_link_4: "Opening explorer",
  tool_online_classes: "Online Classes",
  tool_classes_desc:
    "Learn from grandmasters and certified instructors through live interactive sessions.",
  tool_classes_link_1: "Live instruction",
  tool_classes_link_2: "Video tutorials",
  tool_classes_link_3: "Skill-based curriculum",
  tool_classes_link_4: "Certificate programs",

  // Play page
  ready_to_play_title: "Ready To Play ?",
  ready_to_play_subtitle:
    "Choose your opponent, set the challenge, and start playing.",
  vs_platform: "vs Platform",
  vs_live_player: "vs Live Player",
  select_difficulty: "Select Difficulty",
  easy: "Easy",
  medium: "Medium",
  hard: "Hard",
  beginner_friendly: "Beginner friendly",
  balanced_challenge: "Balanced challenge",
  expert_level: "Expert level",
  find_live_opponent: "Find a live opponent",
  live_matchmaking_desc:
    "Start matchmaking and we will pair you with another player.",

  // Game
  game_locked_message: "The game is locked. Please log in to start playing.",
  finding_opponent: "Finding opponent…",
  connected: "Connected",
  reconnecting: "Reconnecting…",
  matchmaking_waiting: "Matchmaking · waiting for opponent",
  playing_vs_live: "Playing vs Live Player",
  playing_vs_ai: "Playing vs AI ({{level}})",
  live_game: "Live Game",
  chess_game: "Chess Game",
  playing_color: "Playing {{color}}",
  find_opponent_overlay_title: "Finding opponent…",
  find_opponent_overlay_desc:
    "Stay on this page. We will start the game when a player is matched.",
  you_win: "YOU WIN",
  bot_wins: "BOT WINS",
  opponent_wins: "OPPONENT WINS",
  draw_result: "DRAW",
  white_to_move: "White to move",
  black_to_move: "Black to move",
  move_history: "Move History",
  fetching_moves: "Fetching moves…",
  no_moves_yet: "No moves yet",
  total_moves: "Total Moves:",
  current_turn: "Current Turn:",
  choose_board_theme: "Choose Board Theme",
  theme_classic: "Classic",
  theme_brown: "Brown",
  theme_blue: "Blue",
  theme_gray: "Gray",
  theme_red: "Red",
  theme_green: "Green",

  // Analyze
  sign_in_to_analyze: "Sign in to analyze your real games with the engine.",
  analyze_your_games: "Analyze Your Games",
  analyze_subtitle:
    "Deep dive into your games with AI-powered analysis and improve faster.",
  start_analyzing: "Start Analyzing",
  already_have_account_play: "Already have an account? Play a game first",
  game_history: "Game History",
  games_count: "{{count}} games",
  no_games_saved: "No Games Saved Yet",
  play_some_games: "Play some games to see them here!",
  no_game_selected: "No Game Selected",
  select_game_history: "Select a game from the history to analyze its moves",
  stockfish: "Stockfish",
  bot_game: "Bot Game",
  player_game: "Player Game",
  bot_name: "Bot Name",
  all_moves: "All Moves",
  select_game_moves: "Select a game to see its moves",
  no_moves_recorded: "No moves recorded",
  ai_bot: "AI Bot",
  player_id: "Player {{id}}",
  current_move: "Current Move:",
  analyze_btn: "Analyze",
  ai_insights_desc: "Get AI insights and best move suggestions as you navigate",
  analyzing_position: "Analyzing position…",
  analysis_unavailable: "Analysis unavailable. Try again in a moment.",
  ai_label: "AI",
  engine_suggestion: "Engine suggestion",
  best_line_for: "Best line for {{color}}",
  recommended_move: "Recommended move:",
  alternatives: "Alternatives:",
  no_engine_lines: "No engine lines for this position.",
  use_arrow_keys: "Use ← → arrow keys to navigate moves",
  mate_in: "Mate in {{count}}",

  // Problems
  problems_title: "Problems",
  could_not_load_puzzles: "Could not load puzzles.",
  no_problems_match: "No problems match your filters.",
  showing_problems: "Showing {{shown}} of {{total}} problems",
  filter_all: "All",
  filter_tactical: "Tactical",
  filter_endgame: "Endgame",
  filter_opening: "Opening",
  filter_positional: "Positional",
  difficulty_beginner: "Beginner",
  difficulty_intermediate: "Intermediate",
  difficulty_advanced: "Advanced",
  difficulty_expert: "Expert",
  solve_problem: "Solve Problem",
  could_not_start_puzzle: "Could not start this puzzle. Go back and try again.",
  select_puzzle: "Select a puzzle from the list to start solving.",
  browse_puzzles: "Browse puzzles",
  back_to_puzzles: "Back to puzzles",
  checking_move: "Checking move…",
  your_turn: "Your turn",
  chess_puzzle: "Chess puzzle",
  puzzle: "Puzzle",

  // Profile
  elo_rating: "ELO Rating",
  armenia: "Armenia",
  edit_profile: "Edit Profile",
  upload_photo_hint: "Click the camera icon to upload a new photo",
  nickname_label: "Nickname",
  email_label: "Email",
  country_label: "Country",
  placeholder_choose_username: "Choose a username",
  placeholder_choose_country: "Choose a country",
  achievements: "Achievements",
  achievements_available: "{{count}} available",
  could_not_load_achievements: "Could not load achievements.",
  no_achievements: "No achievements in the catalog yet.",
  locked: "Locked",
  loading_friends: "Loading friends…",
  friends: "Friends",
  friends_count: "Friends ({{count}})",
  no_friends_found: "No friends found.",
  elo_short: "ELO:",
  recent_games: "Recent Games",
  your_latest_matches: "Your latest matches",
  no_recent_games: "No Recent Games Yet",
  recent_games_empty:
    "Your recent game history will appear here once you start playing.",
  updating_puzzle_stats: "Updating puzzle stats…",
  match_results: "Match Results",
  total_games: "Total Games",
  wins: "Wins",
  losses: "Losses",
  draws: "Draws",
  problems_solved: "Problems Solved",
  total_solved: "Total Solved",
  top_players_elo: "Top 10 ELO Leaders",
  add_friends_compare: "Add friends to compare ratings.",
  you_suffix: "· You",
  no_friends_yet: "No friends yet",
  no_friends_search: "Connect with other players from your profile or search.",
  find_players: "Find Players",
  no_friends_match: "No friends match your search.",
  search_friends: "Search friends…",
  could_not_load_profile: "Could not load your profile.",
  puzzle_breakdown_unavailable: "Puzzle breakdown unavailable.",

  // Settings
  settings_title: "Settings",
  password_security: "Password & Security",
  password_security_subtitle:
    "Update your password to keep your account secure",
  current_password: "Current Password",
  new_password: "New Password",
  confirm_new_password: "Confirm New Password",
  placeholder_current_password: "Enter current password",
  placeholder_new_password: "Enter new password",
  placeholder_confirm_new_password: "Confirm New Password",
  notifications_title: "Notifications",
  notifications_subtitle: "Manage how you receive notifications",
  game_invites: "Game Invites",
  game_invites_desc: "Get notified when someone challenges you",
  friend_requests: "Friend Requests",
  friend_requests_desc: "Be notified of new friend requests",
  privacy_title: "Privacy",
  privacy_subtitle: "Control who can see your activity",
  show_online_status: "Show Online Status",
  show_online_status_desc: "Let others know when you're online",

  // Pages & misc
  loading_profile: "Loading profile",
  loading_history: "Loading History…",
  game_analysis: "Game Analysis",
  completing_login: "Completing login...",
  restoring_session: "Restoring session",

  // Footer
  footer_platform: "Platform",
  footer_play_online: "Play Online",
  footer_tournaments: "Tournaments",
  footer_puzzles: "Puzzles",
  footer_analysis_board: "Analysis Board",
  footer_learn: "Learn",
  footer_video_library: "Video Library",
  footer_articles: "Articles",
  footer_opening_db: "Opening Database",
  footer_community: "Community",
  footer_forums: "Forums",
  footer_clubs: "Clubs",
  footer_events: "Events",
  footer_blog: "Blog",
  footer_company: "Company",
  footer_about_us: "About Us",
  footer_careers: "Careers",
  footer_support: "Support",
  footer_contact: "Contact",
  footer_copyright: "© 2026 ChessMaster. All rights reserved.",
  footer_terms: "Terms",
  footer_privacy: "Privacy",
  footer_cookies: "Cookies",

  // About (existing)
  about_title: "About ChessMaster",
  about_subtitle:
    "ChessMaster is a cutting-edge chess platform that combines advanced AI technology with world-class instruction to help players of all levels improve their game.",
  our_story_title: "Our Story",
  our_story_text:
    "I am Nver Stepanyan. I created this platform for those who appreciate quality chess and a clearly working system. My 32 years of experience in chess allow me to clearly distinguish an effective tool from an ordinary program. During these years, I have gone through the path of a professional player and coach, understanding all the advantages and disadvantages of the system. I set a goal to create a system that would be lightweight, fast, and professional—based on real experience. I have created an environment where every detail works for your progress.",
  our_mission_title: "Our Mission",
  our_mission_text:
    "To democratize chess education by providing accessible, AI-powered training tools that help players understand the game at a deeper level.",
  instant_feedback_title: "Instant Feedback",
  instant_feedback_text:
    "Get real-time insights and alternative moves as you analyze your games.",
  deep_understanding_title: "Deep Understanding",
  deep_understanding_text:
    'We explain the "why" behind every move, not just the "what"—helping you develop genuine chess intuition.',
  professional_analysis_title: "Professional Analysis",
  professional_analysis_text:
    "Access the kind of analysis previously available only to elite players with personal coaches.",
  meet_our_team: "Meet Our Team",
  team_role_founder: "Founder",
  team_role_software_engineer: "Software engineer",
  team_role_software_developer: "Software developer",
  team_role_front_end_developer: "Front End Developer",
  team_role_product_designer: "Product Designer",
  team_bio_nver:
    "Chess professional based on 32 years of experience, creating innovative training platform that helps players at all levels.",
  team_bio_aram:
    "Leads the technical architecture and product development of ChessMaster platform.",
  team_bio_tigran:
    "Expert software developer specializing in backend systems and AI integration.",
  team_bio_arthur:
    "Frontend specialist crafting beautiful and responsive user interfaces.",
  team_bio_sona:
    "UX/UI specialist focused on creating intuitive learning experiences for chess players of all levels.",
  ready_title: "Ready to Improve Your Game?",
  ready_description:
    "Join thousands of players who are already using ChessMaster to analyze their games, learn from AI insights, and elevate their chess to the next level.",
  ready_start_playing: "Start Playing",
  ready_watch_demo: "Watch Demo",
} as const;

export type StringKey = keyof typeof baseStrings;
export type UiLang = "en" | "ru" | "am";
